#!/bin/bash
# should this be a docker compose file? maybe
set -Eeu

pushd scrapy
docker build -t clarinetear-scrapy .
popd
pushd import
docker build -t clarinetear-import .
popd
pushd restapi
docker build -t clarinetear-restapi .
popd
pushd front
docker build -t clarinetear-front .
popd

echo '[DEFAULT]' > ./database/yoyo.ini
echo 'batch_mode=on' >> ./database/yoyo.ini

docker run -v $(pwd)/database:/database -w /database clarinetear-import yoyo apply --database sqlite:////database/news.db /import/migrations

docker run clarinetear-scrapy scrapy runspider /scrapy/clarinetear/spiders/clarin.py --nolog -o -:jl | docker run -i -v $(pwd)/database:/database clarinetear-import python3 /import/main.py - /database/news.db
docker run clarinetear-scrapy scrapy runspider /scrapy/clarinetear/spiders/lanacion.py --nolog -o -:jl | docker run -i -v $(pwd)/database:/database clarinetear-import python3 /import/main.py - /database/news.db

docker network create clarinetear || true
docker rm clarinetear-restapi || true
docker run -d --network=clarinetear --name clarinetear-restapi -v $(pwd)/database:/database clarinetear-restapi || true
docker rm clarinetear-front || true
docker run -d --network=clarinetear -p 3001:80 --name clarinetear-front clarinetear-front || true
